### ISSUE TITLE
Build for Mavericks

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/FogBurner#11]
I don't _think_ there's anything that's Yosemite-specific in the code -- my only concern would be the `.button?` property automatically created on the `NSStatusItem` off the top of my head.

It would be swell if this worked on at least Mavericks.

**Comment by tofumatt** [comment]
(Obviously, the app is built with Swift, so 10.9 is as early as we can go, derp!)

**Comment by tofumatt** [comment]
(Finally, changing to 10.9 as a build target works, so we'll go from there!)

**Comment by sarahmonster** [comment]
Current build just has a big old cross-out sign over it if you download it in Mavericks. 

![screenshot 2014-11-23 12 59 17](https://cloud.githubusercontent.com/assets/376315/5156923/95cf0ea0-7310-11e4-958c-53a60bd22a71.png)

**Comment by tofumatt** [comment]
Just added a new version (beta-4) to [fogburner.tofumatt.com](http://fogburner.tofumatt.com/), let me know if that one works.

**Comment by sarahmonster** [comment]
It's launchable now, but nothing appears in my menubar at all.

**Comment by tofumatt** [comment]
Alright, I suspect that’s because of my use of the `.button?` property. I’ll ship another beta today and see if it helps.
