### ISSUE TITLE
Open at Login is not saved

### ISSUE THREAD

**Issue by vinkla** [tofumatt/FogBurner#18]
Seems like the open at login feature works for me. Installed the app via your website. The open at login is always unchecked and I can't find any plist file in my `Preferences` directory.

**Comment by tofumatt** [comment]
Do the other preferences (like the amount of time to keep the display on by default) save? Which beta are you running?
- Matthew Riley MacPherson | tofumatt.com

On 6 December 2014 at 17:46:02, Vincent Klaiber (notifications@github.com) wrote:

Seems like the open at login feature works for me. Installed the app via your website. The open at login is always unchecked and I can't find any plist file in my Preferences directory.

**Comment by vinkla** [comment]
Nothing gets saved. I'm running version 1.0-Beta (5). Each time I open the app the method "firstRun" triggers.

**Comment by tofumatt** [comment]
## Ah, okay, thanks for the bug report! I'll check that out! 

Matthew Riley MacPherson (Sent from mobile)

**Comment by vinkla** [comment]
Great, thanks!

**Comment by vinkla** [comment]
I've tried to solve this in a similar way but with no success. Instead I created a `LaunchAtLogin` class.

``` swift
import Cocoa
import ServiceManagement

class LaunchAtLogin {

    let userDefaults: NSUserDefaults
    var launchAtLogin: Bool
    var errorInfo: AutoreleasingUnsafeMutablePointer<NSDictionary?>

    init() {
        userDefaults = NSUserDefaults.standardUserDefaults()
        launchAtLogin = userDefaults.boolForKey("launchAtLogin")
        errorInfo = AutoreleasingUnsafeMutablePointer<NSDictionary?>()
    }

    func toggle() {
        if (launchAtLogin) {
            disable()
            launchAtLogin = false
        } else {
            enable()
            launchAtLogin = true
        }
        updateDefaults()
    }

    func updateDefaults() {
        userDefaults.setBool(launchAtLogin, forKey: "launchAtLogin")
        userDefaults.synchronize()
    }

    func enable() {
        var tell: String = "tell application \"System Events\"\n"
        var getProperties: String = "get the properties of every login item\n"
        var newItem: String = "make new login item at the end of login items with properties {path: \"/Applications/AppName.app\", hidden: false}\n"
        var endTell: String = "end tell"
        var launchAtLoginScript: NSAppleScript = NSAppleScript(source: tell + getProperties + newItem + endTell)!

        launchAtLoginScript.executeAndReturnError(errorInfo)
    }

    func disable() {
        var tell: String = "tell application \"System Events\"\n"
        var deleteItem: String = "if login item \"AppName\" exists then delete login item \"AppName\"\n"
        var endTell: String = "end tell"
        var launchAtLoginScript: NSAppleScript = NSAppleScript(source: tell + deleteItem + endTell)!

        launchAtLoginScript.executeAndReturnError(errorInfo)

    }

}

```

**Comment by vinkla** [comment]
Sorry about closing, though this was old news.

**Comment by tofumatt** [comment]
No worries, just think it might still be a bug so I'll leave it open for
now until I can confirm it works.

On Monday, 16 March 2015, Vincent Klaiber notifications@github.com wrote:

> Sorry about closing, though this was old news.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tofumatt/FogBurner/issues/18#issuecomment-81691124.

## 
- Matthew Riley MacPherson (Sent from mobile)

**Comment by fwenzel** [comment]
Yeah my wife runs beta 5 and noticed the same thing, open at login does not work.

**Comment by vinkla** [comment]
Closing and cleaning up old issues.
