### ISSUE TITLE
Prevent screen from dimming (on battery?)

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/FogBurner#3]
Currently the `caffeinate` command we shell out to doesn't seem to disable screen dimming, which is an important feature.

**Comment by fwenzel** [comment]
`-u      Create an assertion to declare that user is active.` might be what you want

**Comment by tofumatt** [comment]
Should be fixed with 1c7cb9672cdf52dd6a132fd8d40fead30633b278.
