### ISSUE TITLE
Coffee cup logo?

### ISSUE THREAD

**Issue by fwenzel** [tofumatt/FogBurner#8]
While the eye logo _works_, you're using a coffee cup (vector?) for your main logo. Looks like you should be able to use that for the title bar logo too? Like: cup outline when off, and solid cup with steam when on?

Let me know if I can help.

**Comment by tofumatt** [comment]
That’s my eventual plan; I mostly haven’t been able to get a certain designer to make me a good version of a coffee cup yet ;-)

**Comment by fwenzel** [comment]
Good strategy making a shitty logo until she can't handle it anymore and rescues you ;)

**Comment by tofumatt** [comment]
Related to #10...
